version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
          upload-coverage: true
      - release-management/test-nut:
          name: nuts-on-linux
          sfdx_version: latest
          requires:
            - node-latest
      - release-management/test-nut:
          name: nuts-on-windows
          sfdx_version: latest
          os: windows
          requires:
            - node-latest
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          sign: true
          github-release: true
          requires:
            - node-latest
          filters:
            branches:
              only: main
      - release-management/release-package:
          name: pre-release branch package
          sign: true
          requires:
            - node-latest
            - nuts-on-linux
            - nuts-on-windows
            - node-12
          prerelease: true
          filters:
            branches:
              ignore: main
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
